version: '3.8'

services:
  task-service:
    build:
      context: ./task-service
    ports:
      - "5000:5000"
    container_name: task-service
    networks:
      - todo-network

  user-service:
    build:
      context: ./user-service
    ports:
      - "5001:5001"
    container_name: user-service
    networks:
      - todo-network

  collaboration-service:
    build:
      context: ./collaboration-service
    ports:
      - "4000:4000"
    container_name: collaboration-service
    networks:
      - todo-network

  notification-service:
    build:
      context: ./notification-service
    ports:
      - "5002:5002"
    container_name: notification-service
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge
