version: '3.8'

services:
  task-service:
    build:
      context: ./task-service
    ports:
      - "5000:5000"
    container_name: task-service
    networks:
      - todo-network

  user-service:
    build:
      context: ./user-service
    ports:
      - "5001:5001"
    container_name: user-service
    networks:
      - todo-network

  collaboration-service:
    build:
      context: ./collaboration-service
    ports:
      - "4000:4000"
    container_name: collaboration-service
    networks:
      - todo-network

  notification-service:
    build:
      context: ./notification-service
    ports:
      - "5002:5002"
    container_name: notification-service
    networks:
      - todo-network

  postgres:
    image: postgres:14
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 
      POSTGRES_DB: ctf_todo
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./user-service/migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - todo-network


volumes:
  db_data:

networks:
  todo-network:
    driver: bridge
